### ISSUE TITLE
Better abstraction of reference store

### ISSUE THREAD

**Issue by jstolarek** [jstolarek/slicer#35]
Reference store is an `IntMap`, with store labels being an `Int`. There are some helper functions that work on a store (`deref`, `storeInsert`, `insertStoreHole`). This is all a bit messy. `StoreLabel` should be a newtype, not a type synonym, `Store` should be a record with a map and reference counter (currently handled by `Eval` monad) and it should be completely abstract.

# TODO

  * [x] `StoreLabel` a newtype
  * [x] `StoreLabel` instance of Valuable
  * [x] `StoreLabels` a set
  * [x] `Store` a pair of store and reference count
  * [x] `Store` abstraction used in evaluation and repl monads.

**Comment by jstolarek** [comment]
Also, if `StoreLabel` is a newtype we could make it into an instance of `Valuable`, which would be a nice abstraction. At the moment we have to explicitly wrap it in `VStoreLoc`.

**Comment by jstolarek** [comment]
Also, StoreLabels should be a set.
